export const SERVICE_UNAVAILABLE_ERROR = 'SERVICE_UNAVAILABLE_ERROR'
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR'
export default {
  SERVICE_UNAVAILABLE_ERROR,
  INTERNAL_SERVER_ERROR
}
